#!/usr/bin/env php
<?php

/**
 * PHP Docblock Checker
 *
 * @copyright    Copyright 2014, Block 8 Limited.
 * @license      https://github.com/Block8/php-docblock-checker/blob/master/LICENSE.md
 * @link         http://www.phptesting.org/
 */

include __DIR__.'/vendor/autoload.php';

use PhpDocblockChecker\CheckerApplication;
use PhpDocblockChecker\CheckerCommand;

$command     = new CheckerCommand();
$application = new CheckerApplication();

$application->add($command);
$application->run();
